default:
  hostname: 127.0.0.1
  port: 12201
  local_app_name: rails_application
  facility: rails_application
  max_chunk_size: LAN
  level: 3

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

stage:
  <<: *defaults

demo:
  <<: *defaults
